services:
  kanastra_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanastra_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - kanastra_network
    depends_on:
      - kanastra_db
    ports:
      - "8001:80"

  kanastra_db:
    image: mysql:8.0
    container_name: kanastra_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306" # Porta externa 3307 para evitar conflito com um MySQL local
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - kanastra_network

  kanastra_nginx:
    image: nginx:stable-alpine
    container_name: kanastra_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80" # Porta externa 8081 para evitar conflitos com outro Nginx
    networks:
      - kanastra_network
    depends_on:
      - kanastra_app

volumes:
  dbdata:

networks:
  kanastra_network:
    driver: bridge
